### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by Coderx7** [TheMaverickProgrammer/C-Python-like-Decorators#2]
Hi @TheMaverickProgrammer , 
It was a treat reading your explanation I really did enjoy it and loved it thoroughly thanks a lot. 
I just posted this to suggest you to add your explanation and method at this [SO question ](https://stackoverflow.com/questions/30679445/python-like-c-decorators). 
Keep up the great work 
Best regards

**Comment by Coderx7** [comment]
I also would like to mention that it failed on me  with the error : 
```cpp
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'toTensor': is not a member of 'Benchmark::<lambda_929e3d1091a7c8c41ca1b8507c37c308>'	LibtorchPort\LibtorchPort.cpp	593	
```
This is my C++-decorator: 
```cpp
template<typename F>
auto Benchmark(const F& func)
{
    return [func](auto&&... args)
    {
        std::cout << "*******" << std::endl;
        auto start = std::chrono::high_resolution_clock::now();
        func(std::forward<decltype(args)>(args)...);
        auto end = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double, std::milli> elapsed_ms = end - start;
        std::cout << "elapsed time : " << elapsed_ms.count() << " ms" << std::endl;
        std::cout << std::flush << "\n*******" << std::endl;
    };
}
```
and this is how its called : 
```cpp
at::Tensor output2 = Benchmark(r18.forward(input_to_net2)).toTensor();
```
This is libtorch by the way (Pytorchs C++ wrapper). I'm using Visual Studi 2019, v142 and I have explicitly set language standard on C++14 (as libtorch libs that I have (prebuilt ones) doesnt support higher versions it seems)

It'd be really great to get around this issue. but all in all, I'm still impressed by your work.

**Comment by TheMaverickProgrammer** [comment]
Per the SO, it looks like someone has already posted a link here!

Per your error, this is because you are calling `Benchmark(...)` which returns a lambda function, and that inner-lambda does not return anything. You want to return a Libtorch class type. 

I'm going stick my neck out here and assume that `r18.forward(input_to_net2)` was supposed to return some libtorch class with the `toTensor()` member function. Here's how you would write that:

```cpp
template<typename F>
auto Benchmark(const F& func)
{
    return [func](auto&&... args)
    {
        std::cout << "*******" << std::endl;
        auto start = std::chrono::high_resolution_clock::now();
        auto func_result = func(std::forward<decltype(args)>(args)...);
        auto end = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double, std::milli> elapsed_ms = end - start;
        std::cout << "elapsed time : " << elapsed_ms.count() << " ms" << std::endl;
        std::cout << std::flush << "\n*******" << std::endl;

        return func_result;
    };
}
```

Now it will return a result type (note: this will cause an error if func is type `void`. There are tricks we can use to circumvent this but beyond the scope of this reply.

In order to decorate a class object, you need to visit a member function. You can use a **class visitor** decorator function to achieve this.

```cpp
template<typename F>
auto classmethod(const F& func) {
    return [func](auto& obj, auto&&... args) {
        return (obj.*func)(std::forward<decltype(args)>(args)...);
    };
}
```

Now you must wrap this class function and supply the object you wish to call the member object on. 

```cpp
// I didn't know the type of r18 so I use decltype keyword
auto benchmark_forward_func = Benchmark(classmethod(&(decltype(r18)::forward)));
```

call it like this:

```cpp
at::Tensor output2 = benchmark_forward_func(r18, input_to_net2).toTensor();
```

**Comment by Coderx7** [comment]
@TheMaverickProgrammer Thanks a lot. really appreciate it, yes, after posting the code, I realized I missed the return, but ultimately saw the class method section and used that, but incorrectly the first time until you kindly posted the right way. 
this is what I have now : 
```cpp
 at::Tensor output2 = classmethod(&(decltype(r18)::forward))(r18, input_to_net2).toTensor();
```

Its greatly appreciated and again I really suggest to have a post there, a link doesnt get as much attention since all those methods were not even close to your proposed method + the whole explanation is missing there. anyway its up to you. 
Have a wonderful day ;)

**Comment by TheMaverickProgrammer** [comment]
I updated the README to include the **classmethod** section. I see you forked the project. You'll want to pull and merge this update.
